bb-client:
  url: https://api-testnet.bybit.com
  api-key: 
  api-secret: 
  interval-sec: 15
tg-client:
  token: 
db:
  path: ./bb-client.db  
symbols:
  - BTCUSDT
  - FOXYUSDT
  - FTNUSDT
  - THETAUSDT